apiVersion: apps/latest
kind: Deployment
metadata:
  name: momo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: momo
  template:
    metadata:
      labels:
        app: momo
    spec:
      containers:
      - name: momo
        image: malingmania/momo
        ports:
        - containerPort: 80
