apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsmith-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wordsmith-web
  template:
    metadata:
      labels:
        app: wordsmith-web
    spec:
      containers:
      - name: wordsmith-web
        image: mwene/wordsmith-web:latest
        ports:
        - containerPort: 80
